version: '3.8'

services:
  db:
    image: postgres:14-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: BigBrain_70
      POSTGRES_DB: upload
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # To initialize database
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-multi-threaded-up-down-load-app
    ports:
      - "8989:8989"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: BigBrain_70
      DB_NAME: upload
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
